### ISSUE TITLE
`conda` packaging

### ISSUE THREAD

**Issue by ilaflott** [CMIP-Data-Request/CMIP7_DReq_Software#128]
I've been playing around with the API for a little bit today, and I've thought of a few simple ways to use the API for some straightforward scripts that may help my users. 

I guess what stops me, is our lab's workflow package [fre-cli](https://www.github.com/noaa-gfdl/fre-cli) is primarily a `conda` package. I'm just prototyping, but if i get any of our users attached to what i make, deploying a package dependent on this code is actually tricky for us because of our packaging choice. I don't want to introduce distinct avenues of maintenance in an already challenging computing environment. 

further explanation: listing this package as a requirement in our `meta.yaml` impossible, because *it is only a pip package*. We're prioritizing avoiding tech debt, so that rules out an additional `pip install` target under `build: script:` in `meta.yaml`, or a line in `build.sh`, neither of which is recommended practice by `conda` aficionados. I don't know why exactly, but I'll guess, TLDR, "caches". 

going from `pip` --> `conda` packaging shouldn't be TOO bad. things like `conda skeleton` exist to help migrate such packaging. If `CMIP7_DReq_Software` is willing to do so, I'm willing to explore more embedded usage on our side.

**Comment by wolfiex** [comment]
Hey @ilaflott  from my understanding you would want to include this in the `environment.yaml` rather than the `meta.yaml` file. This should be build directly with conda and not cause any issues. 

```yaml
name: fre-cli
channels:
  - conda-forge
  - noaa-gfdl
dependencies:
  - python==3.11
  - noaa-gfdl::analysis_scripts
  - noaa-gfdl::catalogbuilder
  - noaa-gfdl::fre-nctools
  - conda-forge::click<8.2
  - conda-forge::cylc-flow>=8.2.0
  - conda-forge::cylc-rose
  - conda-forge::cmor>=3.10.0
  - conda-forge::cdo>=2.0.0
  - conda-forge::jsonschema
  - conda-forge::metomi-rose
  - conda-forge::nccmp
  - conda-forge::pylint
  - conda-forge::pytest
  - conda-forge::pytest-cov
  - conda-forge::python-cdo
  - conda-forge::cftime
  - conda-forge::pyyaml
  
  # Add this bit here!
  - pip
  - pip: # Include pip dependencies last
        - CMIP7-data-request-api
```
